name: Add reviewers
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

permissions:
  pull-requests: write

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/github-script@v7.0.1
        with:
          script: |
            try {
              const {user, requested_reviewers} = context.payload.pull_request
              const author = user.login;

              const reviewers = ['Sepulator', 'anastanei', 'SpaNb4', 'IlinJoy'];
              const existingReviewers = requested_reviewers.map(reviewer => reviewer.login);

              const newReviewers = reviewers.filter(reviewer =>
                reviewer !== author && !existingReviewers.includes(reviewer)
              );

              if (newReviewers.length) {
                await github.rest.pulls.requestReviewers({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  reviewers: newReviewers
                });
              }
            } catch (error) {
              console.error(error.message);
            }
